apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dex
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://charts.dexidp.io
    chart: dex
    targetRevision: "0.24.1"
    helm:
      releaseName: dex
      values: |
        config:
          issuer: https://dex.local
          storage:
            type: kubernetes
            config:
              inCluster: true
          oauth2:
            skipApprovalScreen: true
          staticPasswords:
          - email: alice@university.edu
            hash: "$2y$10$fnA.mtZg.VwoBJVpJWiheu/s0oee3twD.l28IiCxJdCS5KNpUEgDy"
            username: alice
            userID: "alice-001"
            groups:
              - researchers
          - email: bob@university.edu
            hash: "$2y$10$fnA.mtZg.VwoBJVpJWiheu/s0oee3twD.l28IiCxJdCS5KNpUEgDy"
            username: bob
            userID: "bob-001"
            groups:
              - researchers
          - email: dave@university.edu
            hash: "$2y$10$fnA.mtZg.VwoBJVpJWiheu/s0oee3twD.l28IiCxJdCS5KNpUEgDy"
            username: dave
            userID: "dave-001"
            groups:
              - janitor
          staticClients:
          - id: jupyterhub
            name: JupyterHub
            secret: jupyterhub-client-secret
            redirectURIs:
            - https://jupyter.local/hub/oauth_callback
  destination:
    server: https://kubernetes.default.svc
    namespace: dex
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        naas.platform/observability: "true"
        pod-security.kubernetes.io/enforce: baseline
        pod-security.kubernetes.io/enforce-version: latest
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true