apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kai-scheduler
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: ghcr.io/kai-scheduler/kai-scheduler
    chart: kai-scheduler
    targetRevision: "v0.16.4"
    helm:
      releaseName: kai-scheduler
      values: |
        global:
          gpuSharing: false
          resourceReservation:
            namespaceLabels:
              pod-security.kubernetes.io/enforce: privileged
              pod-security.kubernetes.io/enforce-version: latest
  destination:
    server: https://kubernetes.default.svc
    namespace: kai-scheduler
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jqPathExpressions:
    - .status
    - .spec.conversion.webhook.clientConfig.caBundle
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/enforce-version: latest
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m