apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-policies
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://github.com/MikeTheBuddy/k8s-platform
    targetRevision: HEAD
    path: platform/policies
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true