apiVersion: policies.kyverno.io/v1
kind: MutatingPolicy
metadata:
  name: enforce-kai-scheduler
spec:
  matchConstraints:
    resourceRules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
      operations: ["CREATE"]
    namespaceSelector:
      matchLabels:
        naas.platform/user-namespace: "true"
  mutations:
  - patchType: ApplyConfiguration
    applyConfiguration:
      expression: |
        Object{
          metadata: Object.metadata{
            labels: {
              "kai.scheduler/queue": namespaceObject.metadata.name
            }
          },
          spec: Object.spec{
            schedulerName: "kai-scheduler"
          }
        }