apiVersion: v1
kind: Namespace
metadata:
  name: naas-system

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: naas-tier-config
  namespace: naas-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  free: |
    cpu:
      request: "100m"
      limit: "300m"
    memory:
      request: "128Mi"
      limit: "128Mi"
    kai:
      cpu: 100
      memory: 128
  standard: |
    cpu:
      request: "250m"
      limit: "500m"
    memory:
      request: "512Mi"
      limit: "512Mi"
    kai:
      cpu: 250
      memory: 512
  pro: |
    cpu:
      request: "1000m"
      limit: "2000m"
    memory:
      request: "1Gi"
      limit: "1Gi"
    kai:
      cpu: 1000
      memory: 1024