apiVersion: kyverno.io/v2
kind: GlobalContextEntry
metadata:
  name: naas-tier-config
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  kubernetesResource:
    group: ""
    version: v1
    resource: configmaps
    namespace: kyverno